services:
  frontend:
    build: ./frontend
    environment: 
      PUBLIC_IP: ${PUBLIC_IP}
    ports:
      - "5000:80"
    networks:
      - frontend-backend
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - frontend-backend
      - backend-db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: platzhalter
    networks:
      - backend-db
    volumes:
      - mysql-example-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  backend-db:
  frontend-backend:
volumes:
  mysql-example-data:
  db-init: